<a href="https://colab.research.google.com/github/Architha-sketch/Python-for-DataScience/blob/main/Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#2-D Array
import numpy as np

test_scores = np.random.randint(0, 101, size=(4, 4))
print(test_scores)
column_means = np.mean(test_scores, axis=0)
row_means = np.mean(test_scores, axis=1)

print("Column-wise means:", column_means)
print("Row-wise means:", row_means)
std_dev = np.std(test_scores)
variance = np.var(test_scores)

print("Standard Deviation:", std_dev)
print("Variance:", variance)
min_value = np.min(test_scores)
max_value = np.max(test_scores)
min_index = np.argmin(test_scores)
max_index = np.argmax(test_scores)

print("Minimum value:", min_value)
print("Maximum value:", max_value)
print("Index of minimum value:", min_index)
print("Index of maximum value:", max_index)

[[19 29 15 69]
 [14 40 17 19]
 [63 16  1  9]
 [84 24 25 82]]
Column-wise means: [45.   27.25 14.5  44.75]
Row-wise means: [33.   22.5  22.25 53.75]
Standard Deviation: 25.77516973755944
Variance: 664.359375
Minimum value: 1
Maximum value: 84
Index of minimum value: 10
Index of maximum value: 12


In [2]:
#Create 3d array
import numpy as np
rgb_image = np.random.randint(0, 256, size=(3, 3, 3))
print(rgb_image)
red_channel = rgb_image[:, :, 0]
green_channel = rgb_image[:, :, 1]
blue_channel = rgb_image[:, :, 2]

print("Red Channel:\n", red_channel)
print("Green Channel:\n", green_channel)
print("Blue Channel:\n", blue_channel)
red_mean = np.mean(red_channel)
green_mean = np.mean(green_channel)
blue_mean = np.mean(blue_channel)

print(f"Average pixel intensity for Red channel: {red_mean}")
print(f"Average pixel intensity for Green channel: {green_mean}")
print(f"Average pixel intensity for Blue channel: {blue_mean}")
brightness_increase = 50
brightened_image = np.clip(rgb_image + brightness_increase, 0, 255)
print("Brightened Image (clipped at 255):\n", brightened_image)

[[[217 141  92]
  [ 37 101  25]
  [146  12 141]]

 [[115 183 237]
  [ 57 110  25]
  [127  40  78]]

 [[155 138  95]
  [147  46 250]
  [110 201  60]]]
Red Channel:
 [[217  37 146]
 [115  57 127]
 [155 147 110]]
Green Channel:
 [[141 101  12]
 [183 110  40]
 [138  46 201]]
Blue Channel:
 [[ 92  25 141]
 [237  25  78]
 [ 95 250  60]]
Average pixel intensity for Red channel: 123.44444444444444
Average pixel intensity for Green channel: 108.0
Average pixel intensity for Blue channel: 111.44444444444444
Brightened Image (clipped at 255):
 [[[255 191 142]
  [ 87 151  75]
  [196  62 191]]

 [[165 233 255]
  [107 160  75]
  [177  90 128]]

 [[205 188 145]
  [197  96 255]
  [160 251 110]]]
